// Builds src/data/europe.js from Natural Earth (world-atlas) 50m country outlines.
// Projection: Lambert azimuthal equal-area centred on 10°E, 50°N, fitted to a 1000-unit-wide box.
import fs from 'fs';
import { feature } from 'topojson-client';

const topo = JSON.parse(fs.readFileSync('node_modules/world-atlas/countries-50m.json', 'utf8'));
const fc = feature(topo, topo.objects.countries);
const D = Math.PI / 180, lon0 = 10 * D, lat0 = 50 * D;
function proj([lon, lat]) {
  const l = lon * D, p = lat * D;
  const k = Math.sqrt(2 / (1 + Math.sin(lat0) * Math.sin(p) + Math.cos(lat0) * Math.cos(p) * Math.cos(l - lon0)));
  return [k * Math.cos(p) * Math.sin(l - lon0), -k * (Math.cos(lat0) * Math.sin(p) - Math.sin(lat0) * Math.cos(p) * Math.cos(l - lon0))];
}
// Map window (lon/lat corners define the projected clip rectangle)
const corners = [[-10.5, 36], [30, 36], [-10.5, 60.5], [30, 60.5], [10, 60.5], [10, 36]].map(proj);
let x0 = -0.33, x1 = 0.33, y0 = -0.19, y1 = 0.25;
const W = 1000, S = W / (x1 - x0), H = Math.round((y1 - y0) * S);
const tx = ([x, y]) => [(x - x0) * S, (y - y0) * S];

function clip(poly) { // Sutherland–Hodgman against [0,W]x[0,H]
  const edges = [p => p[0] >= 0, p => p[0] <= W, p => p[1] >= 0, p => p[1] <= H];
  const inter = (a, b, k) => {
    const [ax, ay] = a, [bx, by] = b;
    if (k < 2) { const X = k === 0 ? 0 : W; const t = (X - ax) / (bx - ax); return [X, ay + t * (by - ay)]; }
    const Y = k === 2 ? 0 : H; const t = (Y - ay) / (by - ay); return [ax + t * (bx - ax), Y];
  };
  let out = poly;
  edges.forEach((inside, k) => {
    const inp = out; out = [];
    for (let i = 0; i < inp.length; i++) {
      const cur = inp[i], prev = inp[(i + inp.length - 1) % inp.length];
      if (inside(cur)) { if (!inside(prev)) out.push(inter(prev, cur, k)); out.push(cur); }
      else if (inside(prev)) out.push(inter(prev, cur, k));
    }
  });
  return out;
}
function rdp(pts, eps) {
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts[pts.length - 1]];
  let md = 0, mi = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const [px, py] = pts[i];
    const dx = b[0] - a[0], dy = b[1] - a[1];
    const d = Math.abs(dy * px - dx * py + b[0] * a[1] - b[1] * a[0]) / (Math.hypot(dx, dy) || 1);
    if (d > md) { md = d; mi = i; }
  }
  if (md > eps) return rdp(pts.slice(0, mi + 1), eps).slice(0, -1).concat(rdp(pts.slice(mi), eps));
  return [a, b];
}
const area = p => Math.abs(p.reduce((s, [x, y], i) => { const [X, Y] = p[(i + 1) % p.length]; return s + x * Y - X * y; }, 0) / 2);
const out = [];
for (const f of fc.features) {
  const g = f.geometry; if (!g) continue;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.type === 'MultiPolygon' ? g.coordinates : [];
  const res = [];
  for (const poly of polys) {
    const ring = poly[0];
    if (!ring.some(([lon, lat]) => lon > -25 && lon < 45 && lat > 30 && lat < 72)) continue;
    let pts = ring.map(proj).map(tx);
    pts = clip(pts);
    if (pts.length < 3) continue;
    { // split the closed ring at its farthest vertex so RDP has two distinct endpoints
      let fi = 0, fd = 0; pts.forEach(([x, y], i) => { const d = Math.hypot(x - pts[0][0], y - pts[0][1]); if (d > fd) { fd = d; fi = i; } });
      const A = rdp(pts.slice(0, fi + 1), 1.1), B = rdp([...pts.slice(fi), pts[0]], 1.1);
      pts = A.slice(0, -1).concat(B.slice(0, -1));
    }
    if (pts.length < 3 || area(pts) < 40) continue;
    res.push(pts.map(([x, y]) => [Math.round(x * 10) / 10, Math.round(y * 10) / 10]));
  }
  if (res.length) out.push({ id: f.id, name: f.properties.name, polys: res });
}
// helper: project lon/lat for placing features
const place = (lon, lat) => tx(proj([lon, lat])).map(v => Math.round(v));
const cities = { berlin: place(13.4, 52.5), paris: place(2.35, 48.85), edersee: place(9.05, 51.18), kassel: place(9.5, 51.3) };
const js = `// Generated by tools/build_map.mjs from Natural Earth 1:50m (public domain) via world-atlas.\n// Lambert azimuthal equal-area centred on 10°E 50°N; units: map box ${W} x ${H}.\nwindow.EUROPE = ${JSON.stringify({ W, H, cities, countries: out })};\n`;
fs.writeFileSync('src/data/europe.js', js);
console.log('countries', out.length, 'size', W, H, 'bytes', js.length, cities);
console.log(out.map(c => c.name).join(', '));
